//! Stored Skill folders and the one place that resolves where they live.
//!
//! A published Skill is a folder, not a file: `SKILL.md` plus the references,
//! scripts and templates its instructions point at. Vibex keeps that folder in
//! its own store rather than writing straight into an Agent's Skills folder,
//! because there is more than one Agent and only one copy of the Skill.
//!
//! The store sits beside the database, so it belongs to the same installation
//! the Skill rows do. That matters for the desktop's isolated preview and
//! release-channel homes: a preview build reads its own database, and it reads
//! the Skill folders stored beside it rather than the stable build's.
//!
//! Two writers use this module and they have to agree on the layout: the market
//! install writes a folder, and the native export reads one back to copy it
//! into an Agent's Skills folder. Deriving the path in one function is what
//! keeps them from drifting apart.

use std::fs;
use std::path::{Path, PathBuf};

use vibex_core::{Skill, SkillId, SkillMarketBundleFile, SkillSourceKind, VibexError, VibexResult};

/// Directory, beside the database, that holds every market-installed Skill.
pub(crate) const MARKET_SKILL_STORE_DIR: &str = "market-skills";
/// Name a Skill's manifest is stored under.
pub(crate) const SKILL_MANIFEST_FILE: &str = "SKILL.md";

/// Root of the store for one installation.
pub(crate) fn market_skill_store_root(db_path: &Path) -> PathBuf {
    // A database with no parent is a bare file name in the working directory,
    // so the store lands beside it rather than inside a path that is not there.
    db_path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."))
        .join(MARKET_SKILL_STORE_DIR)
}

/// Folder one Skill's bundle occupies.
pub(crate) fn market_skill_dir(store_root: &Path, skill_id: &SkillId) -> PathBuf {
    // A `SkillId` is generated by Vibex as `skill_<uuid>`, so it is already a
    // single safe path segment and needs no escaping.
    store_root.join(skill_id.as_str())
}

/// Write one Skill folder, replacing whatever was there.
///
/// The directory is cleared first rather than merged: a Skill that dropped a
/// reference in its latest release must not keep serving the old one, and the
/// folder on disk is supposed to be the bundle the user approved, not the union
/// of every bundle ever approved.
pub(crate) fn write_skill_bundle(
    directory: &Path,
    manifest: &str,
    files: &[SkillMarketBundleFile],
) -> VibexResult<()> {
    if directory.exists() {
        fs::remove_dir_all(directory).map_err(|error| {
            VibexError::storage(
                "market_skill_store_clear_failed",
                format!(
                    "the previous Skill folder at {} could not be replaced: {error}",
                    directory.display()
                ),
            )
        })?;
    }
    fs::create_dir_all(directory).map_err(|error| {
        VibexError::storage(
            "market_skill_store_create_failed",
            format!(
                "the Skill folder at {} could not be created: {error}",
                directory.display()
            ),
        )
    })?;
    let manifest_path = directory.join(SKILL_MANIFEST_FILE);
    fs::write(&manifest_path, manifest).map_err(|error| {
        VibexError::storage(
            "market_skill_store_write_failed",
            format!("{} could not be written: {error}", manifest_path.display()),
        )
    })?;
    for file in files {
        // The path was already confined to the Skill folder when the archive
        // was read; joining it here is what puts the assets beside the
        // manifest. `create_dir_all` covers the nested case (`references/x.md`).
        let target = directory.join(&file.path);
        if let Some(parent) = target.parent()
            && let Err(error) = fs::create_dir_all(parent)
        {
            return Err(VibexError::storage(
                "market_skill_store_create_failed",
                format!("{} could not be created: {error}", parent.display()),
            ));
        }
        fs::write(&target, &file.content).map_err(|error| {
            VibexError::storage(
                "market_skill_store_write_failed",
                format!("{} could not be written: {error}", target.display()),
            )
        })?;
    }
    Ok(())
}

/// Folder a Skill's files are copied from, when it has one on disk.
///
/// A `LocalFolder` Skill keeps its folder where the user put it and records the
/// manifest path in `source_uri`. A market-installed Skill keeps its folder in
/// the store above, keyed by its id. Anything else — a hand-written Skill, an
/// imported one whose folder is gone — has no folder, and only its manifest
/// travels.
///
/// The directory is checked rather than assumed: a row that outlived its folder
/// must degrade to a manifest-only export instead of producing an export that
/// fails, because the Agent can still use the instructions.
pub(crate) fn skill_source_dir(skill: &Skill, store_root: Option<&Path>) -> Option<PathBuf> {
    if skill.source_kind == SkillSourceKind::Marketplace
        && let Some(store_root) = store_root
    {
        let directory = market_skill_dir(store_root, &skill.id);
        if directory.is_dir() {
            return Some(directory);
        }
    }
    let path = PathBuf::from(skill.source_uri.as_deref()?);
    let parent = path.parent()?;
    parent.is_dir().then(|| parent.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    use vibex_core::{SkillMarketBundleFile, SkillScopeKind, SkillStatus, unix_timestamp_ms};

    fn skill(source_kind: SkillSourceKind, source_uri: Option<String>) -> Skill {
        let now = unix_timestamp_ms();
        Skill {
            id: SkillId::new(),
            display_name: "Demo".to_string(),
            source_kind,
            status: SkillStatus::Enabled,
            scope_kind: SkillScopeKind::User,
            project_id: None,
            workspace_id: None,
            source_uri,
            description: None,
            tags: Vec::new(),
            content_preview: None,
            body: Some("Body".to_string()),
            provider_matrix: Vec::new(),
            agent_matrix: Vec::new(),
            created_at_ms: now,
            updated_at_ms: now,
            deleted_at_ms: None,
        }
    }

    fn file(path: &str, content: &str) -> SkillMarketBundleFile {
        SkillMarketBundleFile {
            path: path.to_string(),
            content: content.to_string(),
            bytes: content.len() as u64,
        }
    }

    #[test]
    fn the_store_sits_beside_the_database() {
        let root = market_skill_store_root(Path::new("/home/user/.vibex/vibex.db"));
        assert_eq!(root, PathBuf::from("/home/user/.vibex/market-skills"));
        // A bare file name has no parent directory to land in, so the store
        // falls back to the working directory rather than to a path that is
        // not there.
        assert_eq!(
            market_skill_store_root(Path::new("vibex.db")),
            PathBuf::from("./market-skills")
        );
    }

    #[test]
    fn a_bundle_is_written_as_a_real_skill_folder() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("market-skills");
        let skill = skill(
            SkillSourceKind::Marketplace,
            Some("market:o/demo".to_string()),
        );
        let bundle = market_skill_dir(&root, &skill.id);

        write_skill_bundle(
            &bundle,
            "---\nname: Demo\n---\n\nBody\n",
            &[
                file("references/api.md", "api notes"),
                file("scripts/fill.py", "print(1)"),
            ],
        )
        .unwrap();

        assert_eq!(
            fs::read_to_string(bundle.join(SKILL_MANIFEST_FILE)).unwrap(),
            "---\nname: Demo\n---\n\nBody\n"
        );
        // A nested asset lands in its own directory, because the exporter reads
        // the folder back by walking it.
        assert_eq!(
            fs::read_to_string(bundle.join("references").join("api.md")).unwrap(),
            "api notes"
        );
        assert_eq!(
            fs::read_to_string(bundle.join("scripts").join("fill.py")).unwrap(),
            "print(1)"
        );
    }

    #[test]
    fn reinstalling_replaces_the_folder_rather_than_merging_into_it() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("market-skills");
        let skill = skill(
            SkillSourceKind::Marketplace,
            Some("market:o/demo".to_string()),
        );
        let bundle = market_skill_dir(&root, &skill.id);

        write_skill_bundle(
            &bundle,
            "first",
            &[file("references/old.md", "gone"), file("keep.md", "keep")],
        )
        .unwrap();
        write_skill_bundle(&bundle, "second", &[file("keep.md", "keep")]).unwrap();

        // The folder is the bundle that was approved, not the union of every
        // bundle ever approved.
        assert!(!bundle.join("references").join("old.md").exists());
        assert_eq!(fs::read_to_string(bundle.join("keep.md")).unwrap(), "keep");
        assert_eq!(
            fs::read_to_string(bundle.join(SKILL_MANIFEST_FILE)).unwrap(),
            "second"
        );
    }

    #[test]
    fn a_market_skill_resolves_its_folder_from_the_store() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("market-skills");
        let skill = skill(
            SkillSourceKind::Marketplace,
            Some("market:o/demo".to_string()),
        );
        let bundle = market_skill_dir(&root, &skill.id);

        // A row whose folder is not there yet has no source folder; the export
        // then carries the manifest alone.
        assert_eq!(skill_source_dir(&skill, Some(&root)), None);

        fs::create_dir_all(&bundle).unwrap();
        assert_eq!(skill_source_dir(&skill, Some(&root)), Some(bundle.clone()));
        // Without a store root there is nothing to derive, so the row falls
        // back to whatever its `source_uri` names — which here is not a path.
        assert_eq!(skill_source_dir(&skill, None), None);
    }

    #[test]
    fn an_imported_skill_resolves_its_folder_from_source_uri() {
        let dir = tempfile::tempdir().unwrap();
        let folder = dir.path().join("my-skill");
        fs::create_dir_all(&folder).unwrap();
        let manifest = folder.join(SKILL_MANIFEST_FILE);
        fs::write(&manifest, "Body").unwrap();
        let skill = skill(
            SkillSourceKind::LocalFolder,
            Some(manifest.display().to_string()),
        );

        assert_eq!(skill_source_dir(&skill, None), Some(folder));
        // A store root is irrelevant to a Skill that is not a market install.
        assert_eq!(
            skill_source_dir(&skill, Some(&dir.path().join("market-skills"))),
            Some(dir.path().join("my-skill"))
        );
    }

    #[test]
    fn a_skill_whose_folder_is_gone_has_no_source_folder() {
        let dir = tempfile::tempdir().unwrap();
        let missing = skill(
            SkillSourceKind::LocalFolder,
            Some(
                dir.path()
                    .join("gone")
                    .join(SKILL_MANIFEST_FILE)
                    .display()
                    .to_string(),
            ),
        );
        assert_eq!(skill_source_dir(&missing, None), None);

        let manual = skill(SkillSourceKind::Manual, None);
        assert_eq!(skill_source_dir(&manual, Some(dir.path())), None);
    }

    /// The store root is stable across calls, so a writer and a reader that
    /// derive it independently agree without sharing state.
    #[test]
    fn the_store_root_does_not_depend_on_the_call() {
        let path = Path::new("/tmp/example/vibex.db");
        assert_eq!(market_skill_store_root(path), market_skill_store_root(path));
        std::thread::sleep(Duration::from_millis(1));
        assert_eq!(market_skill_store_root(path), market_skill_store_root(path));
    }
}
